version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-container
    hostname: 9263dcbd9075
    mac_address: 02:42:ac:11:00:02
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: DDD
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - bridge

volumes:
  postgres-data:

networks:
  bridge:
    driver: bridge
